[package]
name = "gtksnake"
version = "0.1.0"
authors = ["Marekkon5"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
glib = "0.10"
gdk = "0.13"
gtk = "0.9"
gio = "0.9"